spring.application.name=task-orchestrator

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/task_orchestrator_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true